export const GET_APPLICATIONS = "GET_APPLICATIONS";
export const POST_APPLICATIONS = "POST_APPLICATIONS";
export const DELETE_APPLICATIONS = "DELETE_APPLICATIONS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const SIGN_UP = "SIGN_UP";
